// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaHsLs7dFSpcCSDZgk2O5w0XSYqEUEPWE',
    appId: '1:331108660865:web:20a6c7a9930a537ba23f80',
    messagingSenderId: '331108660865',
    projectId: 'causeways-live',
    authDomain: 'causeways-live.firebaseapp.com',
    storageBucket: 'causeways-live.appspot.com',
    measurementId: 'G-ZJRHRRWVT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYIhuNjQ7LTWotzwP19tY4sxRQr3u5JgM',
    appId: '1:331108660865:android:7a9e6031e301b250a23f80',
    messagingSenderId: '331108660865',
    projectId: 'causeways-live',
    storageBucket: 'causeways-live.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD69V4nmHHDsZlM5OLxNfyUk8x6GtWu3JE',
    appId: '1:331108660865:ios:f5a9d3ab463246a0a23f80',
    messagingSenderId: '331108660865',
    projectId: 'causeways-live',
    storageBucket: 'causeways-live.appspot.com',
    iosClientId: '331108660865-sc3a2q703tdtiicbu8p1kidmgql6kphf.apps.googleusercontent.com',
    iosBundleId: 'coa',
  );
}
